# include: package:lints/recommended.yaml
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    constant_identifier_names : false
    always_declare_return_types : true
    camel_case_types : true
    prefer_single_quotes : true
    sort_child_properties_last : true
    cascade_invocations : false


# analyzer:
#   exclude:
#     - path/to/excluded/files/**
