name: mutation_test
description: A command line application to measure the quality of your test cases by mutating your code and checking if your tests detect the changes.
version: 1.2.2
homepage: https://domohuhn.github.io/mutation-test/
repository: https://github.com/domohuhn/mutation-test
issue_tracker: https://github.com/domohuhn/mutation-test/issues

environment:
  sdk: '>=2.16.0 <3.0.0'

executables:
  mutation_test:

dependencies:
  args: ^2.3.0
  xml: ^6.0.0

dev_dependencies:
  lints: ^1.0.1
  flutter_oss_licenses: ^2.0.0
  test: ^1.16.0

platforms:
  linux:
  macos:
  windows:

