name: mutation_test
description: A command line application to measure the quality of your test cases by mutating your code and checking if your tests detect the changes.
version: 1.3.4
homepage: https://domohuhn.github.io/mutation-test/
repository: https://github.com/domohuhn/mutation-test
issue_tracker: https://github.com/domohuhn/mutation-test/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  mutation_test:

dependencies:
  args: ^2.3.1
  xml: ^6.2.2

dev_dependencies:
  flutter_oss_licenses: ^2.0.1
  test: ^1.22.2
  very_good_analysis: ^3.1.0

platforms:
  linux:
  macos:
  windows:

